### ISSUE TITLE
Configuration Not added to web.config from Nuget

### ISSUE THREAD

**Issue by paulmcgann** [BVNetwork/Newsletter#1]
Hi

I don't know if this is really an issue or more something that needs corrected.

In the Readme.md it says 'configuration is added to web.config' however when I installed using nuget it did not install the configuration in the web.config also you make reference to 3.2.0 however the version on nuget is 3.1.0 would it be possible to update the nuget feed?

Thanks

**Comment by evest** [comment]
Unfortunately, the readme and the nuget packages are not in sync at the moment. I've done a major rewrite of the recipient provider functionality, removing duplicate code, cleaning up a bit and added the configuration section in order to have better control of what providers you want to enable.

The 3.1.0 package is configured differently, and this documentation is valid for that version: https://github.com/BVNetwork/Newsletter/blob/3a47eb362db602e0f110feba511a838c30f410fc/readme.md

Since I haven't been able to fully test the 3.2.0 package yet, I haven't added it to the feed. If you want to help test, I can provide the 3.2.0 packages here.

Sorry for the inconvenience caused by getting out of sync (oh, I just found a reason to branch :-)
